"""Postfix general parameters stored in DB and rendered to main.cf.override."""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, Field, model_validator

from app.db import db

# Postfix defaults (Debian package / postconf -d)
DEFAULT_MESSAGE_SIZE_LIMIT = 10_240_000  # 10 MB
DEFAULT_MAILBOX_SIZE_LIMIT = 51_200_000  # 50 MB
DEFAULT_SMTPD_TIMEOUT = 300  # seconds

DEFAULT_SETTINGS: dict[str, Any] = {
    "message_size_limit": DEFAULT_MESSAGE_SIZE_LIMIT,
    "mailbox_size_limit": DEFAULT_MAILBOX_SIZE_LIMIT,
    "smtpd_timeout": DEFAULT_SMTPD_TIMEOUT,
}


class PostfixSettings(BaseModel):
    message_size_limit: int = Field(
        default=DEFAULT_MESSAGE_SIZE_LIMIT,
        ge=1_048_576,
        le=104_857_600,
        description="Maximum message size in bytes (in transit)",
    )
    mailbox_size_limit: int = Field(
        default=DEFAULT_MAILBOX_SIZE_LIMIT,
        ge=1_048_576,
        le=524_288_000,
        description="Maximum mailbox size in bytes",
    )
    smtpd_timeout: int = Field(
        default=DEFAULT_SMTPD_TIMEOUT,
        ge=30,
        le=3600,
        description="SMTP client idle timeout in seconds",
    )

    @model_validator(mode="after")
    def mailbox_at_least_message_size(self) -> PostfixSettings:
        if self.mailbox_size_limit < self.message_size_limit:
            raise ValueError(
                "mailbox_size_limit must be greater than or equal to message_size_limit"
            )
        return self


def normalize_settings(raw: dict[str, Any] | str | None) -> dict[str, Any]:
    if raw is None:
        data: dict[str, Any] = {}
    elif isinstance(raw, str):
        data = json.loads(raw) if raw.strip() else {}
    else:
        data = dict(raw)
    merged = {**DEFAULT_SETTINGS, **{k: v for k, v in data.items() if v is not None}}
    validated = PostfixSettings.model_validate(merged)
    return validated.model_dump()


def get_settings() -> dict[str, Any]:
    with db() as conn:
        row = conn.execute(
            "SELECT json_payload FROM postfix_settings WHERE id = 1"
        ).fetchone()
    if not row:
        return normalize_settings(None)
    return normalize_settings(json.loads(row["json_payload"]))


def persist_settings(settings: dict[str, Any]) -> dict[str, Any]:
    normalized = normalize_settings(settings)
    with db() as conn:
        conn.execute(
            """
            INSERT INTO postfix_settings (id, json_payload) VALUES (1, ?)
            ON CONFLICT(id) DO UPDATE SET json_payload = excluded.json_payload
            """,
            (json.dumps(normalized),),
        )
        conn.commit()
    return normalized


def build_main_override(settings: dict[str, Any] | None = None) -> str:
    s = normalize_settings(settings)
    lines = [
        "# Generated by Mail Exchange — do not edit manually",
        f"message_size_limit = {s['message_size_limit']}",
        f"mailbox_size_limit = {s['mailbox_size_limit']}",
        f"smtpd_timeout = {s['smtpd_timeout']}s",
    ]
    return "\n".join(lines) + "\n"
