import json
import logging
import os
import re
from pathlib import Path

from app.db import DATA_DIR, GENERATED_DIR, db
from app.relay_ips import relay_client_access_filename, relay_source_ips_from_db
from app.spamassassin import build_amavis_overrides, build_local_cf
from app.system_settings import POSTFIX_HOSTNAME, get_settings, write_docker_dns_compose_override

logger = logging.getLogger(__name__)


def write_caddy_env() -> None:
    settings = get_settings()
    token = (settings.get("cloudflare_api_token") or "").strip()
    lines = [f"CLOUDFLARE_API_TOKEN={token}" if token else "CLOUDFLARE_API_TOKEN=", ""]
    env_path = GENERATED_DIR / "caddy.env"
    env_path.write_text("\n".join(lines), encoding="utf-8")
    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass


def write_caddyfile() -> None:
    settings = get_settings()
    hostname = settings["public_url"]
    email = settings["acme_email"]
    token = (settings.get("cloudflare_api_token") or "").strip()
    tls_block = ""
    if token:
        tls_block = """
\ttls {
\t\tdns cloudflare {$CLOUDFLARE_API_TOKEN}
\t\tresolvers 1.1.1.1 1.0.0.1 8.8.8.8
\t}"""
    content = f"""# Generated by Mail Exchange — do not edit manually
{{
\temail {email}
}}

{hostname} {{{tls_block}
\treverse_proxy mx-frontend:80
}}
"""
    (GENERATED_DIR / "Caddyfile").write_text(content, encoding="utf-8")
    write_caddy_env()

OPENDKIM_DIR = GENERATED_DIR / "opendkim"
DKIM_PUB_DIR = GENERATED_DIR / "dkim"

POSTMASTER_NO_ADMIN_TRANSPORT = (
    "error:5.1.3 Postmaster forwarding is not configured (no admin notify_email)"
)


def admin_notify_emails(conn) -> list[str]:
    rows = conn.execute(
        """
        SELECT DISTINCT LOWER(TRIM(notify_email)) AS email
        FROM users
        WHERE role = 'admin'
          AND notify_email IS NOT NULL
          AND TRIM(notify_email) != ''
        ORDER BY email COLLATE NOCASE
        """
    ).fetchall()
    return [row["email"] for row in rows]


def regenerate_files() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    OPENDKIM_DIR.mkdir(parents=True, exist_ok=True)
    DKIM_PUB_DIR.mkdir(parents=True, exist_ok=True)

    with db() as conn:
        domains = conn.execute(
            """
            SELECT id, name, dkim_selector, relay_all_inbound, relay_source_ips
            FROM domains
            WHERE enabled = 1
            ORDER BY name
            """
        ).fetchall()
        destination_rows = conn.execute(
            """
            SELECT domain_id, host, port
            FROM domain_destinations
            ORDER BY domain_id, id
            """
        ).fetchall()
        rows = conn.execute(
            """
            SELECT m.email, m.destination_host, m.destination_port
            FROM mailboxes m
            INNER JOIN domains d ON d.id = m.domain_id
            WHERE m.enabled = 1 AND d.enabled = 1
            ORDER BY m.email
            """
        ).fetchall()
        raw_settings = conn.execute(
            "SELECT json_payload FROM spam_settings WHERE id = 1"
        ).fetchone()["json_payload"]
        spam_settings = json.loads(raw_settings)
        admin_emails = admin_notify_emails(conn)

    first_destination_by_domain: dict[int, tuple[str, int]] = {}
    for dest in destination_rows:
        domain_id = int(dest["domain_id"])
        if domain_id not in first_destination_by_domain:
            first_destination_by_domain[domain_id] = (
                dest["host"].strip(),
                int(dest["port"]),
            )

    virtual_mailbox_maps_lines = []
    virtual_mailbox_catchall_lines = ["# Generated by Mail Exchange — do not edit manually"]
    transport_maps_lines = []
    for row in rows:
        email = row["email"].strip().lower()
        host = row["destination_host"].strip()
        port = int(row["destination_port"])
        virtual_mailbox_maps_lines.append(f"{email} OK")
        transport_maps_lines.append(f"{email} smtp:[{host}]:{port}")

    domain_names = {row["name"].strip().lower() for row in domains}
    virtual_alias_lines = [f"{row['name']} OK" for row in domains]
    postfix_hostname = POSTFIX_HOSTNAME.strip().lower()
    if postfix_hostname and postfix_hostname not in domain_names:
        virtual_alias_lines.append(f"{postfix_hostname} OK")

    virtual_alias_maps_lines: list[str] = []
    postmaster_hostname_addr = f"postmaster@{postfix_hostname}"
    virtual_mailbox_maps_lines.append(f"{postmaster_hostname_addr} OK")
    if admin_emails:
        virtual_alias_maps_lines.append(
            f"{postmaster_hostname_addr} {', '.join(admin_emails)}"
        )
        for email in admin_emails:
            transport_maps_lines.append(f"{email} smtp:")
    else:
        logger.warning(
            "postmaster@%s: no admin notify_email configured; mail will be rejected",
            postfix_hostname,
        )
        transport_maps_lines.append(
            f"{postmaster_hostname_addr} {POSTMASTER_NO_ADMIN_TRANSPORT}"
        )

    for row in domains:
        dest = first_destination_by_domain.get(int(row["id"]))
        if not dest:
            continue
        host, port = dest
        name = row["name"]
        postmaster = f"postmaster@{name}"
        virtual_mailbox_maps_lines.append(f"{postmaster} OK")
        transport_maps_lines.append(f"{postmaster} smtp:[{host}]:{port}")

    for row in domains:
        if not row["relay_all_inbound"]:
            continue
        dest = first_destination_by_domain.get(int(row["id"]))
        name = row["name"].strip().lower()
        if not dest:
            logger.warning(
                "relay_all_inbound enabled for %s but no destination configured; "
                "catch-all relay skipped",
                name,
            )
            continue
        host, port = dest
        escaped_domain = re.escape(name)
        virtual_mailbox_catchall_lines.append(f"/^.+@{escaped_domain}$/ OK")
        transport_maps_lines.append(f"@{name} smtp:[{host}]:{port}")

    (GENERATED_DIR / "virtual_mailbox_maps").write_text(
        "\n".join(virtual_mailbox_maps_lines)
        + ("\n" if virtual_mailbox_maps_lines else ""),
        encoding="utf-8",
    )
    (GENERATED_DIR / "transport_maps").write_text(
        "\n".join(transport_maps_lines) + ("\n" if transport_maps_lines else ""),
        encoding="utf-8",
    )
    (GENERATED_DIR / "virtual_alias_domains").write_text(
        "\n".join(virtual_alias_lines) + ("\n" if virtual_alias_lines else ""),
        encoding="utf-8",
    )
    (GENERATED_DIR / "virtual_alias_maps").write_text(
        "\n".join(virtual_alias_maps_lines)
        + ("\n" if virtual_alias_maps_lines else ""),
        encoding="utf-8",
    )
    (GENERATED_DIR / "virtual_mailbox_catchall").write_text(
        "\n".join(virtual_mailbox_catchall_lines) + "\n",
        encoding="utf-8",
    )

    # Outbound relay: envelope sender @domain may relay when client IP is listed
    # on that domain's relay_source_ips (see relay_ips.py for full policy).
    relay_sender_access_lines = [
        "# Generated by Mail Exchange — do not edit manually",
        "# @domain -> check_client_access against per-domain cidr map",
    ]
    active_relay_cidr_files: set[str] = set()
    for row in domains:
        name = row["name"].strip().lower()
        relay_ips = relay_source_ips_from_db(row["relay_source_ips"])
        if not relay_ips:
            continue
        cidr_filename = relay_client_access_filename(name)
        cidr_path = GENERATED_DIR / cidr_filename
        cidr_lines = [f"{cidr}\tOK" for cidr in relay_ips]
        cidr_path.write_text("\n".join(cidr_lines) + "\n", encoding="utf-8")
        active_relay_cidr_files.add(cidr_filename)
        cidr_map_ref = f"cidr:/etc/postfix/generated/{cidr_filename}"
        relay_sender_access_lines.append(f"@{name}\tcheck_client_access {cidr_map_ref}")
        relay_sender_access_lines.append(f"{name}\tcheck_client_access {cidr_map_ref}")

    for stale in GENERATED_DIR.glob("relay_client_access_*.cidr"):
        if stale.name not in active_relay_cidr_files:
            stale.unlink(missing_ok=True)

    (GENERATED_DIR / "relay_sender_access").write_text(
        "\n".join(relay_sender_access_lines) + "\n",
        encoding="utf-8",
    )

    key_table_lines = []
    signing_table_lines = []
    domains_list_lines = []
    for row in domains:
        name = row["name"]
        selector = (row["dkim_selector"] or "mail").strip()
        key_file = f"/etc/opendkim/keys/{name}/{selector}.private"
        dkim_name = f"{selector}._domainkey.{name}"
        key_table_lines.append(f"{dkim_name} {name}:{selector}:{key_file}")
        signing_table_lines.append(f"*@{name} {dkim_name}")
        domains_list_lines.append(f"{name}:{selector}")

    (OPENDKIM_DIR / "KeyTable").write_text(
        "\n".join(key_table_lines) + ("\n" if key_table_lines else ""),
        encoding="utf-8",
    )
    (OPENDKIM_DIR / "SigningTable").write_text(
        "\n".join(signing_table_lines) + ("\n" if signing_table_lines else ""),
        encoding="utf-8",
    )
    (OPENDKIM_DIR / "domains.list").write_text(
        "\n".join(domains_list_lines) + ("\n" if domains_list_lines else ""),
        encoding="utf-8",
    )

    (GENERATED_DIR / "spamassassin.local.cf").write_text(
        build_local_cf(spam_settings), encoding="utf-8"
    )
    (GENERATED_DIR / "amavis-spam-overrides.conf").write_text(
        build_amavis_overrides(spam_settings), encoding="utf-8"
    )
    write_caddyfile()
    write_docker_dns_compose_override()

    # Legacy single-key path (first enabled domain) for older tooling
    legacy_key = DKIM_PUB_DIR / f"{domains[0]['name']}.pub" if domains else None
    if legacy_key and legacy_key.exists():
        (GENERATED_DIR / "dkim-public.key").write_text(
            legacy_key.read_text(encoding="utf-8"), encoding="utf-8"
        )
    elif not domains and (GENERATED_DIR / "dkim-public.key").exists():
        pass
    else:
        first_pub = next(DKIM_PUB_DIR.glob("*.pub"), None) if DKIM_PUB_DIR.exists() else None
        if first_pub:
            (GENERATED_DIR / "dkim-public.key").write_text(
                first_pub.read_text(encoding="utf-8"), encoding="utf-8"
            )
