import json
import logging
import os
import re
from pathlib import Path

from app import db as db_module
from app.db import DATA_DIR, GENERATED_DIR, db
from app.mail_config import (
    AMAVIS_SPAM_OVERRIDES,
    POSTFIX_GENERATED_DIR,
    SPAMASSASSIN_LOCAL_CF,
    ensure_mail_config_dirs,
)
from app.relay_ips import (
    relay_client_access_filename,
    relay_restriction_class_name,
    relay_source_ips_from_db,
)
from app.imap_auth import build_imap_auth_config
from app.postfix_settings import build_main_override, get_settings as get_postfix_settings
from app.spamassassin import build_amavis_overrides, build_local_cf
from app.system_settings import POSTFIX_HOSTNAME, get_settings, write_docker_dns_compose_override

logger = logging.getLogger(__name__)


def cloudflare_acme_enabled() -> bool:
    return bool(os.environ.get("CLOUDFLARE_API_TOKEN", "").strip())


def write_caddyfile() -> None:
    settings = get_settings()
    hostname = settings["public_url"]
    email = settings["acme_email"]
    token = cloudflare_acme_enabled()
    global_block = f"""# Generated by Mail Exchange — do not edit manually
{{
\temail {email}
}}
"""
    if token:
        # Con token: HTTP su :80 per IP/fallback; HTTPS con LE DNS-01 solo sul FQDN.
        content = (
            global_block
            + """
:80 {
\treverse_proxy mx-frontend:80
}

"""
            + f"""https://{hostname} {{
\ttls {{
\t\tdns cloudflare {{$CLOUDFLARE_API_TOKEN}}
\t\tresolvers 1.1.1.1 1.0.0.1 8.8.8.8
\t}}
\treverse_proxy mx-frontend:80
}}
"""
        )
    else:
        # Senza token: HTTP su :80 per qualsiasi Host (IP o FQDN); HTTPS solo su :443 con cert interno.
        content = (
            global_block
            + """
:80 {
\treverse_proxy mx-frontend:80
}

"""
            + f"""https://{hostname} {{
\ttls internal
\treverse_proxy mx-frontend:80
}}
"""
        )
    (GENERATED_DIR / "Caddyfile").write_text(content, encoding="utf-8")

OPENDKIM_DIR = GENERATED_DIR / "opendkim"
DKIM_PUB_DIR = GENERATED_DIR / "dkim"

POSTMASTER_NO_ADMIN_TRANSPORT = (
    "error:5.1.3 Postmaster forwarding is not configured (no admin notify_email)"
)


def _dedupe_map_lines(lines: list[str]) -> list[str]:
    seen: set[str] = set()
    deduped: list[str] = []
    for line in lines:
        key = line.split(maxsplit=1)[0].lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append(line)
    return deduped


def admin_notify_emails(conn) -> list[str]:
    rows = conn.execute(
        """
        SELECT DISTINCT LOWER(TRIM(notify_email)) AS email
        FROM users
        WHERE role = 'admin'
          AND notify_email IS NOT NULL
          AND TRIM(notify_email) != ''
        ORDER BY email COLLATE NOCASE
        """
    ).fetchall()
    return [row["email"] for row in rows]


def _add_postmaster_routing(
    postmaster_addr: str,
    *,
    admin_emails: list[str],
    virtual_mailbox_maps_lines: list[str],
    virtual_alias_maps_lines: list[str],
    transport_maps_lines: list[str],
    admin_outbound_transports: set[str],
) -> None:
    """Route postmaster@* to admin notify_email (not backend mailboxes)."""
    addr = postmaster_addr.strip().lower()
    virtual_mailbox_maps_lines.append(f"{addr} OK")
    if admin_emails:
        virtual_alias_maps_lines.append(f"{addr} {', '.join(admin_emails)}")
        for email in admin_emails:
            transport_line = f"{email} smtp:"
            if transport_line not in admin_outbound_transports:
                admin_outbound_transports.add(transport_line)
                transport_maps_lines.append(transport_line)
        return
    logger.warning(
        "%s: no admin notify_email configured; notifications will be rejected",
        addr,
    )
    transport_maps_lines.append(f"{addr} {POSTMASTER_NO_ADMIN_TRANSPORT}")


def write_imap_auth_config(conn=None) -> None:
    """Write /data/sasl/imap_auth.json for Postfix saslauthd IMAP verification."""
    config_path = db_module.DATA_DIR / "sasl" / "imap_auth.json"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    if conn is None:
        with db() as owned:
            config = build_imap_auth_config(owned)
    else:
        config = build_imap_auth_config(conn)
    config_path.write_text(
        json.dumps(config, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def regenerate_files() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    ensure_mail_config_dirs()
    OPENDKIM_DIR.mkdir(parents=True, exist_ok=True)
    DKIM_PUB_DIR.mkdir(parents=True, exist_ok=True)

    with db() as conn:
        domains = conn.execute(
            """
            SELECT id, name, dkim_selector, relay_all_inbound, relay_source_ips
            FROM domains
            WHERE enabled = 1
            ORDER BY name
            """
        ).fetchall()
        destination_rows = conn.execute(
            """
            SELECT domain_id, host, port
            FROM domain_destinations
            ORDER BY domain_id, id
            """
        ).fetchall()
        rows = conn.execute(
            """
            SELECT m.email, m.destination_host, m.destination_port
            FROM mailboxes m
            INNER JOIN domains d ON d.id = m.domain_id
            WHERE m.enabled = 1 AND d.enabled = 1
            ORDER BY m.email
            """
        ).fetchall()
        raw_settings = conn.execute(
            "SELECT json_payload FROM spam_settings WHERE id = 1"
        ).fetchone()["json_payload"]
        spam_settings = json.loads(raw_settings)
        admin_emails = admin_notify_emails(conn)
        write_imap_auth_config(conn)

    destinations_by_domain: dict[int, list[tuple[str, int]]] = {}
    for dest in destination_rows:
        domain_id = int(dest["domain_id"])
        destinations_by_domain.setdefault(domain_id, []).append(
            (dest["host"].strip(), int(dest["port"]))
        )

    def primary_destination(domain_id: int) -> tuple[str, int] | None:
        dests = destinations_by_domain.get(domain_id, [])
        if not dests:
            return None
        return dests[0]

    def relay_destination(domain_id: int, domain_name: str) -> tuple[str, int] | None:
        dests = destinations_by_domain.get(domain_id, [])
        if not dests:
            return None
        if len(dests) > 1:
            logger.warning(
                "relay_all_inbound enabled for %s but %d destinations configured; "
                "using the first by id",
                domain_name,
                len(dests),
            )
        return dests[0]

    virtual_mailbox_maps_lines = []
    virtual_mailbox_catchall_lines = ["# Generated by Mail Exchange — do not edit manually"]
    transport_maps_lines = []
    transport_catchall_lines = ["# Generated by Mail Exchange — do not edit manually"]
    for row in rows:
        email = row["email"].strip().lower()
        host = row["destination_host"].strip()
        port = int(row["destination_port"])
        virtual_mailbox_maps_lines.append(f"{email} OK")
        transport_maps_lines.append(f"{email} smtp:[{host}]:{port}")

    domain_names = {row["name"].strip().lower() for row in domains}
    virtual_alias_lines = [f"{row['name'].strip().lower()} OK" for row in domains]
    postfix_hostname = POSTFIX_HOSTNAME.strip().lower()
    if postfix_hostname and postfix_hostname not in domain_names:
        virtual_alias_lines.append(f"{postfix_hostname} OK")

    virtual_alias_maps_lines: list[str] = []
    admin_outbound_transports: set[str] = set()
    _add_postmaster_routing(
        f"postmaster@{postfix_hostname}",
        admin_emails=admin_emails,
        virtual_mailbox_maps_lines=virtual_mailbox_maps_lines,
        virtual_alias_maps_lines=virtual_alias_maps_lines,
        transport_maps_lines=transport_maps_lines,
        admin_outbound_transports=admin_outbound_transports,
    )

    for row in domains:
        name = row["name"].strip().lower()
        _add_postmaster_routing(
            f"postmaster@{name}",
            admin_emails=admin_emails,
            virtual_mailbox_maps_lines=virtual_mailbox_maps_lines,
            virtual_alias_maps_lines=virtual_alias_maps_lines,
            transport_maps_lines=transport_maps_lines,
            admin_outbound_transports=admin_outbound_transports,
        )

    for row in domains:
        if not row["relay_all_inbound"]:
            continue
        domain_id = int(row["id"])
        name = row["name"].strip().lower()
        dest = relay_destination(domain_id, name)
        if not dest:
            logger.warning(
                "relay_all_inbound enabled for %s but no destination configured; "
                "catch-all relay skipped",
                name,
            )
            continue
        host, port = dest
        transport_route = f"smtp:[{host}]:{port}"
        # virtual_mailbox_maps: @domain OK (hash) plus regexp fallback for local-part.
        virtual_mailbox_maps_lines.append(f"@{name} OK")
        escaped_domain = re.escape(name)
        virtual_mailbox_catchall_lines.append(f"/^.+@{escaped_domain}$/ OK")
        # transport_maps: domain-only key (Postfix transport(5) order); @domain is not used.
        transport_maps_lines.append(f"{name} {transport_route}")
        transport_catchall_lines.append(f"/^.+@{escaped_domain}$/ {transport_route}")

    virtual_mailbox_maps_lines = _dedupe_map_lines(virtual_mailbox_maps_lines)
    transport_maps_lines = _dedupe_map_lines(transport_maps_lines)

    (POSTFIX_GENERATED_DIR / "virtual_mailbox_maps").write_text(
        "\n".join(virtual_mailbox_maps_lines)
        + ("\n" if virtual_mailbox_maps_lines else ""),
        encoding="utf-8",
    )
    (POSTFIX_GENERATED_DIR / "transport_maps").write_text(
        "\n".join(transport_maps_lines) + ("\n" if transport_maps_lines else ""),
        encoding="utf-8",
    )
    (POSTFIX_GENERATED_DIR / "virtual_alias_domains").write_text(
        "\n".join(virtual_alias_lines) + ("\n" if virtual_alias_lines else ""),
        encoding="utf-8",
    )
    (POSTFIX_GENERATED_DIR / "virtual_alias_maps").write_text(
        "\n".join(virtual_alias_maps_lines)
        + ("\n" if virtual_alias_maps_lines else ""),
        encoding="utf-8",
    )
    (POSTFIX_GENERATED_DIR / "virtual_mailbox_catchall").write_text(
        "\n".join(virtual_mailbox_catchall_lines) + "\n",
        encoding="utf-8",
    )
    (POSTFIX_GENERATED_DIR / "transport_catchall").write_text(
        "\n".join(transport_catchall_lines) + "\n",
        encoding="utf-8",
    )

    # Outbound relay: envelope sender @domain may relay when client IP is listed
    # on that domain's relay_source_ips (see relay_ips.py for full policy).
    # Postfix requires smtpd_restriction_classes (check_client_access cannot be
    # nested directly in relay_sender_access).
    relay_sender_access_lines = [
        "# Generated by Mail Exchange — do not edit manually",
        "# @domain -> smtpd_restriction_classes entry",
    ]
    relay_class_lines = [
        "# Generated by Mail Exchange — do not edit manually",
        "# Format: smtpd_restriction_classes <names...>",
        "#         <class_name> <restriction list>",
    ]
    active_relay_cidr_files: set[str] = set()
    active_relay_class_names: list[str] = []
    for row in domains:
        name = row["name"].strip().lower()
        relay_ips = relay_source_ips_from_db(row["relay_source_ips"])
        if not relay_ips:
            continue
        cidr_filename = relay_client_access_filename(name)
        cidr_path = POSTFIX_GENERATED_DIR / cidr_filename
        cidr_lines = [f"{cidr}\tOK" for cidr in relay_ips]
        cidr_path.write_text("\n".join(cidr_lines) + "\n", encoding="utf-8")
        active_relay_cidr_files.add(cidr_filename)
        class_name = relay_restriction_class_name(name)
        active_relay_class_names.append(class_name)
        cidr_map_ref = f"cidr:/etc/postfix/generated/{cidr_filename}"
        relay_class_lines.append(
            f"{class_name} check_client_access {cidr_map_ref}, reject"
        )
        relay_sender_access_lines.append(f"@{name}\t{class_name}")
        relay_sender_access_lines.append(f"{name}\t{class_name}")

    for stale in POSTFIX_GENERATED_DIR.glob("relay_client_access_*.cidr"):
        if stale.name not in active_relay_cidr_files:
            stale.unlink(missing_ok=True)

    relay_class_lines.append(
        "smtpd_restriction_classes " + " ".join(active_relay_class_names)
    )
    (POSTFIX_GENERATED_DIR / "relay_restriction_classes").write_text(
        "\n".join(relay_class_lines) + "\n",
        encoding="utf-8",
    )
    (POSTFIX_GENERATED_DIR / "relay_sender_access").write_text(
        "\n".join(relay_sender_access_lines) + "\n",
        encoding="utf-8",
    )

    # Union of all per-domain relay CIDRs → trusted relay clients (Postfix 3.6+
    # requires permit_mynetworks in smtpd_recipient_restrictions for outbound relay).
    relay_mynetworks_lines: list[str] = []
    seen_relay_cidrs: set[str] = set()
    for row in domains:
        for cidr in relay_source_ips_from_db(row["relay_source_ips"]):
            if cidr not in seen_relay_cidrs:
                seen_relay_cidrs.add(cidr)
                relay_mynetworks_lines.append(f"{cidr}\tOK")
    relay_mynetworks_path = POSTFIX_GENERATED_DIR / "relay_mynetworks.cidr"
    if relay_mynetworks_lines:
        relay_mynetworks_path.write_text(
            "\n".join(relay_mynetworks_lines) + "\n",
            encoding="utf-8",
        )
    else:
        relay_mynetworks_path.unlink(missing_ok=True)

    key_table_lines = []
    signing_table_lines = []
    domains_list_lines = []
    for row in domains:
        name = row["name"]
        selector = (row["dkim_selector"] or "mail").strip()
        key_file = f"/etc/opendkim/keys/{name}/{selector}.private"
        dkim_name = f"{selector}._domainkey.{name}"
        key_table_lines.append(f"{dkim_name} {name}:{selector}:{key_file}")
        signing_table_lines.append(f"*@{name} {dkim_name}")
        domains_list_lines.append(f"{name}:{selector}")

    (OPENDKIM_DIR / "KeyTable").write_text(
        "\n".join(key_table_lines) + ("\n" if key_table_lines else ""),
        encoding="utf-8",
    )
    (OPENDKIM_DIR / "SigningTable").write_text(
        "\n".join(signing_table_lines) + ("\n" if signing_table_lines else ""),
        encoding="utf-8",
    )
    (OPENDKIM_DIR / "domains.list").write_text(
        "\n".join(domains_list_lines) + ("\n" if domains_list_lines else ""),
        encoding="utf-8",
    )

    SPAMASSASSIN_LOCAL_CF.write_text(build_local_cf(spam_settings), encoding="utf-8")
    AMAVIS_SPAM_OVERRIDES.write_text(
        build_amavis_overrides(spam_settings, admin_emails=admin_emails),
        encoding="utf-8",
    )
    write_caddyfile()
    write_docker_dns_compose_override()
    (POSTFIX_GENERATED_DIR / "main.cf.override").write_text(
        build_main_override(get_postfix_settings()),
        encoding="utf-8",
    )

    # Legacy single-key path (first enabled domain) for older tooling
    legacy_key = DKIM_PUB_DIR / f"{domains[0]['name']}.pub" if domains else None
    if legacy_key and legacy_key.exists():
        (GENERATED_DIR / "dkim-public.key").write_text(
            legacy_key.read_text(encoding="utf-8"), encoding="utf-8"
        )
    elif not domains and (GENERATED_DIR / "dkim-public.key").exists():
        pass
    else:
        first_pub = next(DKIM_PUB_DIR.glob("*.pub"), None) if DKIM_PUB_DIR.exists() else None
        if first_pub:
            (GENERATED_DIR / "dkim-public.key").write_text(
                first_pub.read_text(encoding="utf-8"), encoding="utf-8"
            )
