"""SpamAssassin settings schema, defaults, and local.cf generation (Webmin-style groups)."""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, Field

DEFAULT_SETTINGS: dict[str, Any] = {
    "whitelist_from": [],
    "blacklist_from": [],
    "whitelist_to": [],
    "scores": {},
    "classification": {
        "required_score": 5.0,
        "use_bayes": True,
        "bayes_auto_learn": True,
        "use_network_tests": True,
        "skip_rbl": False,
        "rbl_timeout": 15,
        "mx_check_count": 0,
        "mx_check_delay": 6,
        "trusted_networks": "127.0.0.0/8 [::1]/128",
        "ok_languages": "all",
        "ok_locales": "all",
    },
    "report": {
        "rewrite_subject": True,
        "subject_tag": "***SPAM*** ",
        "report_safe": False,
        "report_header_only": False,
        "add_spam_level_header": True,
        "spam_level_char": "*",
        "report_terse": False,
        "clear_report_template": False,
        "report_body": "",
    },
    "network": {
        "dns_available": True,
    },
    "amavis": {
        "tag_level": -999.0,
        "kill_level": 8.0,
        "dsn_cutoff_level": 10.0,
        "sync_kill_with_score": True,
    },
}


class ClassificationSettings(BaseModel):
    required_score: float = Field(default=5.0, ge=0.1, le=50)
    use_bayes: bool = True
    bayes_auto_learn: bool = True
    use_network_tests: bool = True
    skip_rbl: bool = False
    rbl_timeout: int = Field(default=15, ge=1, le=120)
    mx_check_count: int = Field(default=0, ge=0, le=10)
    mx_check_delay: int = Field(default=6, ge=0, le=60)
    trusted_networks: str = "127.0.0.0/8 [::1]/128"
    ok_languages: str = "all"
    ok_locales: str = "all"


class ReportSettings(BaseModel):
    rewrite_subject: bool = True
    subject_tag: str = "***SPAM*** "
    report_safe: bool = False
    report_header_only: bool = False
    add_spam_level_header: bool = True
    spam_level_char: str = "*"
    report_terse: bool = False
    clear_report_template: bool = False
    report_body: str = ""


class NetworkSettings(BaseModel):
    dns_available: bool = True


class AmavisSpamSettings(BaseModel):
    tag_level: float = Field(default=-999.0, ge=-999, le=50)
    kill_level: float = Field(default=8.0, ge=1, le=50)
    dsn_cutoff_level: float = Field(default=10.0, ge=1, le=50)
    sync_kill_with_score: bool = True


class SpamSettings(BaseModel):
    whitelist_from: list[str] = []
    blacklist_from: list[str] = []
    whitelist_to: list[str] = []
    scores: dict[str, float] = {}
    classification: ClassificationSettings = Field(default_factory=ClassificationSettings)
    report: ReportSettings = Field(default_factory=ReportSettings)
    network: NetworkSettings = Field(default_factory=NetworkSettings)
    amavis: AmavisSpamSettings = Field(default_factory=AmavisSpamSettings)


def _deep_merge(base: dict[str, Any], patch: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def normalize_settings(raw: dict[str, Any] | str | None) -> dict[str, Any]:
    if raw is None:
        data: dict[str, Any] = {}
    elif isinstance(raw, str):
        data = json.loads(raw) if raw.strip() else {}
    else:
        data = dict(raw)
    merged = _deep_merge(DEFAULT_SETTINGS, data)
    validated = SpamSettings.model_validate(merged)
    return validated.model_dump()


def build_local_cf(settings: dict[str, Any]) -> str:
    s = normalize_settings(settings)
    clf = s["classification"]
    rep = s["report"]
    net = s["network"]
    network_tests = clf["use_network_tests"] and not clf["skip_rbl"]
    dns_ok = network_tests and net["dns_available"]
    lines: list[str] = [
        "# Generated by Mail Exchange — do not edit manually",
        f"required_score {clf['required_score']}",
        f"use_bayes {'1' if clf['use_bayes'] else '0'}",
        f"bayes_auto_learn {'1' if clf['bayes_auto_learn'] else '0'}",
        f"dns_available {'yes' if dns_ok else 'no'}",
    ]
    if clf["mx_check_count"] > 0:
        lines.append(f"mx_check {clf['mx_check_count']}")
        lines.append(f"mx_check_delay {clf['mx_check_delay']}")
    trusted = clf["trusted_networks"].strip()
    if trusted:
        lines.append(f"trusted_networks {trusted}")
    if clf["ok_languages"] and clf["ok_languages"] != "all":
        for lang in clf["ok_languages"].replace(",", " ").split():
            lang = lang.strip()
            if lang:
                lines.append(f"ok_languages {lang}")
    if clf["ok_locales"] and clf["ok_locales"] != "all":
        for loc in clf["ok_locales"].replace(",", " ").split():
            loc = loc.strip()
            if loc:
                lines.append(f"ok_locales {loc}")
    if rep["rewrite_subject"]:
        tag = rep["subject_tag"].replace('"', '\\"')
        lines.append(f'rewrite_header Subject {tag}%s')
    if rep["report_safe"]:
        lines.append("report_safe 1")
    if rep["report_header_only"]:
        lines.append("report_header_only 1")
    if rep["add_spam_level_header"]:
        ch = (rep["spam_level_char"] or "*")[:1]
        lines.append(f"add_header all X-Spam-Level {ch}")
    if rep["report_terse"]:
        lines.append("report_terse 1")
    if rep["clear_report_template"] and rep["report_body"].strip():
        body = rep["report_body"].strip().replace("\n", "\\n")
        lines.append(f"report {body}")
    for addr in s["whitelist_from"]:
        lines.append(f"whitelist_from {addr}")
    for addr in s["blacklist_from"]:
        lines.append(f"blacklist_from {addr}")
    for addr in s["whitelist_to"]:
        lines.append(f"whitelist_to {addr}")
    for rule, value in s["scores"].items():
        lines.append(f"score {rule} {value}")
    return "\n".join(lines) + "\n"


def build_amavis_overrides(settings: dict[str, Any]) -> str:
    s = normalize_settings(settings)
    clf = s["classification"]
    rep = s["report"]
    av = s["amavis"]
    tag2 = clf["required_score"]
    kill = av["kill_level"]
    if av["sync_kill_with_score"]:
        kill = max(tag2 + 2.0, av["kill_level"])
    subject_tag = rep["subject_tag"].replace("'", "\\'")
    modifies = 1 if rep["rewrite_subject"] else 0
    return "\n".join(
        [
            "# Generated by Mail Exchange — Amavis spam thresholds",
            f"$sa_tag_level_deflt  = {av['tag_level']};",
            f"$sa_tag2_level_deflt = {tag2};",
            f"$sa_kill_level_deflt = {kill};",
            f"$sa_dsn_cutoff_level = {av['dsn_cutoff_level']};",
            f"$sa_spam_subject_tag = '{subject_tag}';",
            f"$sa_spam_modifies_subj = {modifies};",
            "",
        ]
    )
