import ipaddress
import json
import os
import re
from urllib.parse import urlparse

from fastapi import HTTPException
from pydantic import BaseModel, Field

from app.db import GENERATED_DIR, db

POSTFIX_HOSTNAME = os.environ.get("POSTFIX_HOSTNAME", "mx.local")
DEFAULT_ACME_EMAIL = os.environ.get("ACME_EMAIL", "admin@example.com")
DEFAULT_PUBLIC_URL = os.environ.get("CADDY_DOMAIN", POSTFIX_HOSTNAME).strip()
DEFAULT_CADDY_HTTP_PORT = int(os.environ.get("CADDY_HTTP_PORT", "60080"))
DEFAULT_CADDY_HTTPS_PORT = int(os.environ.get("CADDY_HTTPS_PORT", "60443"))
DEFAULT_DOCKER_DNS = [
    ip.strip()
    for ip in re.split(r"[\s,]+", os.environ.get("DOCKER_DNS_SERVERS", "208.67.222.222 208.67.220.220"))
    if ip.strip()
] or ["208.67.222.222", "208.67.220.220"]

HOST_PATTERN = re.compile(
    r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$",
    re.IGNORECASE,
)

MX_SERVICES = (
    "api",
    "frontend",
    "caddy",
    "postfix",
    "amavis",
    "opendkim",
    "clamav",
)


class SystemSettingsUpdate(BaseModel):
    public_url: str = Field(min_length=1, max_length=253)
    acme_email: str = Field(min_length=3, max_length=254)
    docker_dns_servers: str = Field(default="")
    cloudflare_api_token: str | None = None
    clear_cloudflare_token: bool = False


def normalize_public_hostname(value: str) -> str:
    raw = value.strip()
    if not raw:
        raise HTTPException(status_code=400, detail="Public URL is required")
    if "://" in raw:
        parsed = urlparse(raw)
        host = (parsed.hostname or "").strip().lower()
    else:
        host = raw.split("/")[0].split(":")[0].strip().lower()
    if not host or not HOST_PATTERN.match(host):
        raise HTTPException(
            status_code=400,
            detail="Enter a valid hostname (e.g. smtp.example.com), without path",
        )
    return host


def normalize_docker_dns(value: str | list[str] | None) -> list[str]:
    if value is None:
        return list(DEFAULT_DOCKER_DNS)
    if isinstance(value, list):
        parts = [str(item).strip() for item in value]
    else:
        parts = [part.strip() for part in re.split(r"[\s,;]+", str(value)) if part.strip()]

    if not parts:
        return list(DEFAULT_DOCKER_DNS)

    normalized: list[str] = []
    for part in parts[:4]:
        try:
            addr = ipaddress.ip_address(part)
        except ValueError as exc:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid DNS server address: {part}",
            ) from exc
        normalized.append(str(addr))

    return normalized


def _default_settings() -> dict:
    return {
        "public_url": DEFAULT_PUBLIC_URL,
        "acme_email": DEFAULT_ACME_EMAIL,
        "docker_dns": list(DEFAULT_DOCKER_DNS),
        "cloudflare_api_token": "",
    }


def settings_for_api(settings: dict | None = None) -> dict:
    """Return settings safe for API/UI (secrets redacted)."""
    data = dict(settings or get_settings())
    token = (data.pop("cloudflare_api_token", "") or "").strip()
    data["cloudflare_token_configured"] = bool(token)
    data["caddy_http_port"] = DEFAULT_CADDY_HTTP_PORT
    data["caddy_https_port"] = DEFAULT_CADDY_HTTPS_PORT
    return data


def get_settings() -> dict:
    with db() as conn:
        row = conn.execute(
            "SELECT json_payload FROM system_settings WHERE id = 1"
        ).fetchone()
    if not row:
        return _default_settings()
    data = json.loads(row["json_payload"])
    merged = _default_settings()
    merged.update({k: v for k, v in data.items() if v is not None})
    merged["docker_dns"] = normalize_docker_dns(merged.get("docker_dns"))
    return merged


def get_public_hostname() -> str:
    settings = get_settings()
    host = (settings.get("public_url") or "").strip()
    return host or POSTFIX_HOSTNAME


def get_docker_dns_servers() -> list[str]:
    return get_settings().get("docker_dns", list(DEFAULT_DOCKER_DNS))


def docker_dns_servers_text(settings: dict | None = None) -> str:
    servers = (settings or get_settings()).get("docker_dns", DEFAULT_DOCKER_DNS)
    return "\n".join(servers)


def write_docker_dns_compose_override() -> None:
    servers = get_docker_dns_servers()
    dns_yaml = ", ".join(servers)
    lines = [
        "# Generated by Mail Exchange — DNS resolver per container Docker",
        "# Applica con: docker compose -f docker-compose.yml -f docker-dns.override.yml up -d",
        "services:",
    ]
    for service in MX_SERVICES:
        lines.append(f"  {service}:")
        lines.append(f"    dns: [{dns_yaml}]")
    lines.append("")
    (GENERATED_DIR / "docker-dns.override.yml").write_text("\n".join(lines), encoding="utf-8")

    env_lines = ["# Generated by Mail Exchange — variabili DNS Docker"]
    for idx, server in enumerate(servers[:4], start=1):
        env_lines.append(f"DOCKER_DNS_{idx}={server}")
    for idx in range(len(servers) + 1, 5):
        env_lines.append(f"DOCKER_DNS_{idx}=")
    env_lines.append("")
    (GENERATED_DIR / "docker-dns.env").write_text("\n".join(env_lines), encoding="utf-8")


def _resolve_cloudflare_token(payload: SystemSettingsUpdate, existing: dict) -> str:
    if payload.clear_cloudflare_token:
        return ""
    if payload.cloudflare_api_token is not None:
        return payload.cloudflare_api_token.strip()
    return (existing.get("cloudflare_api_token") or "").strip()


def update_settings(payload: SystemSettingsUpdate) -> dict:
    existing = get_settings()
    normalized = {
        "public_url": normalize_public_hostname(payload.public_url),
        "acme_email": payload.acme_email.strip(),
        "docker_dns": normalize_docker_dns(payload.docker_dns_servers),
        "cloudflare_api_token": _resolve_cloudflare_token(payload, existing),
    }
    with db() as conn:
        conn.execute(
            """
            INSERT INTO system_settings (id, json_payload) VALUES (1, ?)
            ON CONFLICT(id) DO UPDATE SET json_payload = excluded.json_payload
            """,
            (json.dumps(normalized),),
        )
        conn.commit()
    write_docker_dns_compose_override()
    result = settings_for_api(normalized)
    result["docker_dns_servers"] = docker_dns_servers_text(normalized)
    return result
